####
# GitLab CI
####

# Image
image: openjdk:8-jdk-alpine

# Variables
variables:
  # Submodule Support (Hugo)
  GIT_SUBMODULE_STRATEGY: recursive

# Cache
cache:
  key: gradle
  paths:
  - .gradle/wrapper
  - .gradle/caches

# Stages
stages:
- build
- test
- docs
- publishStage
- publishStable

# Build
Assemble:
  stage: build
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - ./gradlew assemble

# Test
Run Tests:
  stage: test
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - ./gradlew test

###
# Test Documentation
###
test:
  image: registry.gitlab.com/pages/hugo:latest
  stage: test
  script:
  - cd docs
  - hugo

###
# Build & Publish on GitLab Pages
###
pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: docs
  script:
  - cd docs
  - hugo --baseUrl https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/
  - cp -R public ../
  artifacts:
    paths:
    - public
  only:
  - develop

###
# Pre-Release
###
Publish Prerelease:
  stage: publishStage
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - ./gradlew artifactoryPublish -Dsnapshot=true
  only:
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-alpha\.[0-9]+$/
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-beta\.[0-9]+$/
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-rc\.[0-9]+$/

###
# Stable Release
###
Publish Release:
  stage: publishStable
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - ./gradlew bintrayUpload
  only:
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
